language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - DEFAULT_CODECEPT_FLAGS=""
    - DEFAULT_DB="sqlite"
    - TASK_TESTS_COVERAGE=0

matrix:
  fast_finish: true
  include:
    # run tests coverage on PHP 7.1
    - php: "7.4"
      env:
        - TASK_TESTS_COVERAGE=1

    - php: "7.3"
      env:
        - DEFAULT_DB="psql"

    - php: "7.2"
    - php: "7.1"

services:
  - postgresql

cache:
  directories:
    - ${HOME}/.composer/cache
    - vendor/

install:
  - php --version
  - php -m

  # update extensions
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net

  # install php extensions
  - |
    if (php --version | grep -i HipHop > /dev/null); then
      echo "Skipping imagick and gmagick tests on HHVM"
    else
      pear config-set preferred_state beta
      printf "\n" | pecl install imagick
      # gmagick is not installed on travis currently
      #printf "\n" | pecl install gmagick
    fi
    
  # update composer
  - travis_retry composer self-update && composer --version
  - export PATH="${HOME}/.composer/vendor/bin:${PATH}"
  - travis_retry composer update ${DEFAULT_COMPOSER_FLAGS}

  # set perm
  - |
    cd tests
    codecept build
    chmod -R 0777 app/runtime
    chmod -R 0777 app/web/assets
    chmod +x bin/yii
    cd ../

before_script:
  - echo "VENDOR BIN - $(pwd)/vendor/bin"
  - export PATH="$(pwd)/vendor/bin:${PATH}"
  - composer validate --strict

  # initialize databases
  - |
    if [ ${DEFAULT_DB} == "psql" ]; then
      psql -V
      psql -c "create user test with password 'test';" -U postgres
      psql -c "create database test owner test;" -U postgres
      mv tests/app/config/db.php tests/app/config/db_sqlite.php
      mv tests/app/config/db_psql.php tests/app/config/db.php
    fi

  # apply migrations
  - php ./tests/bin/yii migrate --interactive=0

  # coverage
  - |
    if [ ${TASK_TESTS_COVERAGE} == 1 ]; then
      DEFAULT_CODECEPT_FLAGS="--coverage --coverage-xml --coverage-html"
      # codeclimate
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
      ./cc-test-reporter before-build
    fi

script:
  - |
    cd tests
    # start serve
    php ./bin/yii serve/index > /dev/null 2>&1 &
    # start tests
    php ../vendor/bin/codecept run ${DEFAULT_CODECEPT_FLAGS}
    cd ../

after_script:
  - |
    if [ ${TASK_TESTS_COVERAGE} == 1 ]; then
      mv tests/codeception/_output/coverage.xml clover.xml
      ./cc-test-reporter after-build --coverage-input-type clover \
      --id b724dfc30afed05830bf8583386b61a76b861998f57a174d6b87b5c9bfba4796 \
      --exit-code $TRAVIS_TEST_RESULT
    fi

addons:
  apt:
    packages:
#      - ldap-utils
#      - slapd